# This file was generated by GoReleaser. DO NOT EDIT.
class BackyardsCli < Formula
  desc "Command-line interface for Backyards"
  homepage "https://banzaicloud.com/"
  version "1.0.0-rc.2"

  if OS.mac?
    url "https://github.com/banzaicloud/backyards-cli/releases/download/1.0.0-rc.2/backyards_1.0.0-rc.2_darwin_amd64.tar.gz"
    sha256 "795e66b4de5c065928a997741076b80a22dc8437858f58fd2218da0863dc6954"
  elsif OS.linux?
    url "https://github.com/banzaicloud/backyards-cli/releases/download/1.0.0-rc.2/backyards_1.0.0-rc.2_linux_amd64.tar.gz"
    sha256 "97a62f9257bb12be8da31af6d32d45290ebde3ddc07e9a6f91e188fa023b31dc"
  end

  def install
    bin.install "backyards"
  end

  test do
    system "#{bin}/backyards --version"
  end
end
