# This file was generated by GoReleaser. DO NOT EDIT.
class Backyards < Formula
  desc "Command-line interface for Backyards"
  homepage "https://banzaicloud.com/"
  version "1.4.5"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/banzaicloud/backyards/releases/download/v1.4.5/backyards_1.4.5_darwin_amd64.tar.gz"
    sha256 "ea425baed7b8460d4db14e48e3949053c34e9f074c2bfe33fb62fd541d5e3868"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/banzaicloud/backyards/releases/download/v1.4.5/backyards_1.4.5_linux_amd64.tar.gz"
      sha256 "c3b9da0caf11d25966e5d79ef2c5c6709a5888731c2107e046e184dac786925a"
    end
  end

  def install
    bin.install "backyards"
  end

  test do
    system "#{bin}/backyards --version"
  end
end
