# This file was generated by GoReleaser. DO NOT EDIT.
class Backyards < Formula
  desc "Command-line interface for Backyards"
  homepage "https://banzaicloud.com/"
  version "1.4.5"

  if OS.mac?
    url "https://github.com/banzaicloud/backyards/releases/download/v1.4.5/backyards_1.4.5_darwin_amd64.tar.gz"
    sha256 "df3ef9c1c55d4415d766d53c3d605382736d854f5b39224088ce43246026ff5c"
  elsif OS.linux?
    url "https://github.com/banzaicloud/backyards/releases/download/v1.4.5/backyards_1.4.5_linux_amd64.tar.gz"
    sha256 "67bf93dc6480daf28a392623a8e208609b7d1bc5180c5f5a2def4e8d8c4ea371"
  end

  def install
    bin.install "backyards"
  end

  test do
    system "#{bin}/backyards --version"
  end
end
