# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class BankVaults < Formula
  desc "A Vault swiss-army knife CLI with Kubernetes support"
  homepage "https://banzaicloud.com/products/bank-vaults/"
  version "1.14.3"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/banzaicloud/bank-vaults/releases/download/1.14.3/vault-env-darwin-arm64.tar.gz"
      sha256 "8b7e90f0598b8b80b6637842e5c04c2aeac01df0c9a0aaedb632c5aefe435103"
    end
    if Hardware::CPU.intel?
      url "https://github.com/banzaicloud/bank-vaults/releases/download/1.14.3/vault-env-darwin-amd64.tar.gz"
      sha256 "9986aaaedca28724fd090a9e8b87389e195a1e26e0a500dbf306fe204ead1586"
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/banzaicloud/bank-vaults/releases/download/1.14.3/vault-env-linux-arm64.tar.gz"
      sha256 "247d7ba4dfa192ba0d26fcdcd430a33f3533f884f0be0ee2797b6322815f70d2"
    end
    if Hardware::CPU.intel?
      url "https://github.com/banzaicloud/bank-vaults/releases/download/1.14.3/vault-env-linux-amd64.tar.gz"
      sha256 "a1f326f2adb8c4521bccc6ae5f3dbaecd88cedde214e1314fa859f1a85fa782b"
    end
  end

  def install
    bin.install "vault-env"
  end

  test do
    system "#{bin}/bank-vaults"
    system "#{bin}/vault-env"
  end
end
