# This file was generated by GoReleaser. DO NOT EDIT.
class BanzaiCli < Formula
  desc "Command-line interface for Banzai Cloud Pipeline platform"
  homepage "https://banzaicloud.com/"
  version "0.2.1"

  if OS.mac?
    url "https://github.com/banzaicloud/banzai-cli/releases/download/0.2.1/banzai_0.2.1_darwin_amd64.tar.gz"
    sha256 "3379e6da95d68c7ae18ba726a4bb7466df1c25bb7f8bd25213f35614743abbb6"
  elsif OS.linux?
    url "https://github.com/banzaicloud/banzai-cli/releases/download/0.2.1/banzai_0.2.1_linux_amd64.tar.gz"
    sha256 "e608470e3756e3d01c8cfaec2deea2fab72663c86b842ef6f0f5b5dbdf9b02e4"
  end
  
  depends_on "kubectl"

  def install
    bin.install "banzai"
  end

  test do
    system "#{bin}/banzai --version"
  end
end
