# This file was generated by GoReleaser. DO NOT EDIT.
class BanzaiCli < Formula
  desc "Command-line interface for Banzai Cloud Pipeline platform"
  homepage "https://banzaicloud.com/"
  version "0.0.22"

  if OS.mac?
    url "https://github.com/banzaicloud/banzai-cli/releases/download/0.0.22/banzai_0.0.22_darwin_amd64.tar.gz"
    sha256 "dacb3f26c5b91ea1bd1c672222007334c4c07129c209288cad8bf11f020a0233"
  elsif OS.linux?
    url "https://github.com/banzaicloud/banzai-cli/releases/download/0.0.22/banzai_0.0.22_linux_amd64.tar.gz"
    sha256 "13316d4aff15aa41015fe8a3670d6558b6e0a8c209a3fe42c197bd1860148bd9"
  end
  
  depends_on "kubectl"

  def install
    bin.install "banzai"
  end

  test do
    system "#{bin}/banzai --version"
  end
end
