# This file was generated by GoReleaser. DO NOT EDIT.
class Kurun < Formula
  desc "Run main.go in Kubernetes with one command"
  homepage "https://banzaicloud.com/blog/kurun"
  version "0.3.3"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/banzaicloud/kurun/releases/download/0.3.3/kurun-darwin-amd64.tar.gz"
    sha256 "10792ab62b304c901fc90afb920fae205bcab71fe5492e45d68335bc941cde1a"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/banzaicloud/kurun/releases/download/0.3.3/kurun-linux-amd64.tar.gz"
      sha256 "711020f6dd39d6e8b827c728531320d5727a3c36861a3158c2abc91638743e70"
    end
  end
  
  depends_on "inlets"

  def install
    bin.install "kurun"
  end

  test do
    system "#{bin}/kurun --version"
  end
end
