# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Kurun < Formula
  desc "Run main.go in Kubernetes with one command"
  homepage "https://banzaicloud.com/blog/kurun"
  version "0.5.5"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/banzaicloud/kurun/releases/download/0.5.5/kurun-darwin-amd64.tar.gz"
      sha256 "42667813e950f606bac6ca24997304beb578483d5a9a803ef2b07c0e8896b759"

      def install
        bin.install "kurun"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/banzaicloud/kurun/releases/download/0.5.5/kurun-linux-amd64.tar.gz"
      sha256 "c59a3c5a4ae76dfd2af9aad8fa3614a8feb26904ac12c64cb8dd5003074b6c44"

      def install
        bin.install "kurun"
      end
    end
  end

  depends_on "inlets"

  test do
    system "#{bin}/kurun --version"
  end
end
