# This file was generated by GoReleaser. DO NOT EDIT.
class OneEye < Formula
  desc "Command-line interface for One Eye"
  homepage "https://banzaicloud.com/"
  version "0.4.4"
  bottle :unneeded

  if OS.mac?
    url "https://banzaicloud.com/downloads/one-eye/0.4.4/dist/one-eye_0.4.4_darwin_amd64.tar.gz"
    sha256 "dbfcc6e4877c2e447df1ed9a64e24edda99b80432f76ece7578387598fb967ef"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://banzaicloud.com/downloads/one-eye/0.4.4/dist/one-eye_0.4.4_linux_amd64.tar.gz"
      sha256 "614c36911f22f2b4a55de4d424464738f20d5902a1b821db6692c69776fb011e"
    end
  end

  def install
    bin.install "one-eye"
  end

  test do
    system "#{bin}/one-eye --version"
  end
end
