# This file was generated by GoReleaser. DO NOT EDIT.
class OneEye < Formula
  desc "Command-line interface for One Eye"
  homepage "https://banzaicloud.com/"
  version "0.0.12"

  if OS.mac?
    url "https://banzaicloud.com/downloads/one-eye/0.0.12/dist/one-eye_0.0.12_darwin_amd64.tar.gz"
    sha256 "54920c13d767a57c3c2aa33c564795b23017b8660ee9abe0b10a31565500205a"
  elsif OS.linux?
    url "https://banzaicloud.com/downloads/one-eye/0.0.12/dist/one-eye_0.0.12_linux_amd64.tar.gz"
    sha256 "72025421be700db8049c1ecbc4ab00e68aa3d69e67b4acfd57a70ddde87d3cf1"
  end

  def install
    bin.install "one-eye"
  end

  test do
    system "#{bin}/one-eye --version"
  end
end
