# This file was generated by GoReleaser. DO NOT EDIT.
class SupertubesCli < Formula
  desc "Command-line interface for Supertubes"
  homepage "https://banzaicloud.com/"
  version "0.4.4"

  if OS.mac?
    url "https://banzaicloud.com/downloads/supertubes-cli/0.4.4/dist/supertubes_0.4.4_darwin_amd64.tar.gz"
    sha256 "d2223500d01652b511b26834112a0ba2713336a21cdf9d384cd36929e4247dc2"
  elsif OS.linux?
    url "https://banzaicloud.com/downloads/supertubes-cli/0.4.4/dist/supertubes_0.4.4_linux_amd64.tar.gz"
    sha256 "83bbdf873a9e4bd4245d5c1fc1d9c55db14e723b00c16d5606035e2afbfee949"
  end

  def install
    bin.install "supertubes"
  end

  test do
    system "#{bin}/supertubes --version"
  end
end
