# This file was generated by GoReleaser. DO NOT EDIT.
class SupertubesCli < Formula
  desc "Command-line interface for Supertubes"
  homepage "https://banzaicloud.com/"
  version "0.4.1"

  if OS.mac?
    url "https://banzaicloud.com/downloads/supertubes-cli/0.4.1/dist/supertubes_0.4.1_darwin_amd64.tar.gz"
    sha256 "0d985c3f740971ec61528114bf87ba22d9730407df781dcbe1d12e64f29b5d5d"
  elsif OS.linux?
    url "https://banzaicloud.com/downloads/supertubes-cli/0.4.1/dist/supertubes_0.4.1_linux_amd64.tar.gz"
    sha256 "74f58436efc12b6f746e100e8262092be8826e0a26e133f2befbdb208094c9ce"
  end

  def install
    bin.install "supertubes"
  end

  test do
    system "#{bin}/supertubes --version"
  end
end
