# This file was generated by GoReleaser. DO NOT EDIT.
class SupertubesCli < Formula
  desc "Command-line interface for Supertubes"
  homepage "https://banzaicloud.com/"
  version "0.1.0"

  if OS.mac?
    url "https://banzaicloud.com/downloads/supertubes-cli/0.1.0/dist/supertubes_0.1.0_darwin_amd64.tar.gz"
    sha256 "5b589f2fc4cfe75dfbdadb7b091e736c85a3a66b8d29c9ce7516a577b46138a3"
  elsif OS.linux?
    url "https://banzaicloud.com/downloads/supertubes-cli/0.1.0/dist/supertubes_0.1.0_linux_amd64.tar.gz"
    sha256 "dbaa9cec0734b59d035d5a2b04aad124c8b093867652882262ac2d433fe566d9"
  end

  def install
    bin.install "supertubes"
  end

  test do
    system "#{bin}/supertubes --version"
  end
end
