# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Yami < Formula
  desc "YAML CLI merge tool"
  homepage "https://banzaicloud.com/"
  version "0.0.5-dev.1"

  on_macos do
    url "https://github.com/banzaicloud/yami/releases/download/0.0.5-dev.1/yami_0.0.5-dev.1_darwin_amd64.tar.gz"
    sha256 "ab940fb63be4d32ec5bf355f9ed2e13a99a8eae8f874f60b19404dff43ccde0b"

    def install
      bin.install "yami"
    end

    if Hardware::CPU.arm?
      def caveats
        <<~EOS
          The darwin_arm64 architecture is not supported for the Yami
          formula at this time. The darwin_amd64 binary may work in compatibility
          mode, but it might not be fully supported.
        EOS
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/banzaicloud/yami/releases/download/0.0.5-dev.1/yami_0.0.5-dev.1_linux_amd64.tar.gz"
      sha256 "f86c6a8fa26e2c8bf3b2abf387a8c64cab71a255a9acc65df931ceead2c29446"

      def install
        bin.install "yami"
      end
    end
  end
end
