# This file was generated by GoReleaser. DO NOT EDIT.
class Yami < Formula
  desc "YAML CLI merge tool"
  homepage "https://banzaicloud.com/"
  version "0.0.3"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/banzaicloud/yami/releases/download/0.0.3/yami_0.0.3_darwin_amd64.tar.gz"
    sha256 "66c98590e218a00896cadef2d83d75d710f0c092f77127ff66d0842469de5323"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/banzaicloud/yami/releases/download/0.0.3/yami_0.0.3_linux_amd64.tar.gz"
      sha256 "328817f26f4947ece918704345d4faa84c5363e75ed4733c9562ce6883ed2564"
    end
  end

  def install
    bin.install "yami"
  end
end
