# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Yami < Formula
  desc "YAML CLI merge tool"
  homepage "https://banzaicloud.com/"
  version "0.0.5-dev.3"

  on_macos do
    url "https://github.com/banzaicloud/yami/releases/download/0.0.5-dev.3/yami_0.0.5-dev.3_darwin_amd64.tar.gz"
    sha256 "c85a88935d46f815a2fef8d3f2cb41d2822f1bb361700eb87d0ee64f51476116"

    def install
      bin.install "yami"
    end

    if Hardware::CPU.arm?
      def caveats
        <<~EOS
          The darwin_arm64 architecture is not supported for the Yami
          formula at this time. The darwin_amd64 binary may work in compatibility
          mode, but it might not be fully supported.
        EOS
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/banzaicloud/yami/releases/download/0.0.5-dev.3/yami_0.0.5-dev.3_linux_amd64.tar.gz"
      sha256 "ad81cd150ec1579543426379fa0dea7ff72ba6a8031edf91d43f2260ea22e805"

      def install
        bin.install "yami"
      end
    end
  end
end
